In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
#2 types of arrays 'array arrays' - 'numpy array'
import numpy as np

In [6]:
a = np.array(l)

In [8]:
a

array([23245,    27,   546,   215, -1234])

In [9]:
print(a)

[23245    27   546   215 -1234]


In [10]:
type(a)

numpy.ndarray

In [15]:
b = np.array([12, 455, 63.3, True, "abc"])

In [16]:
b

array(['12', '455', '63.3', 'True', 'abc'], 
      dtype='<U32')

In [17]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [18]:
type(b)

numpy.ndarray

In [19]:
l.pop()

-1234

In [20]:
print(l)

[23245, 27, 546, 215]


In [21]:
a.mean()

4559.8000000000002

---

In [3]:
l = [23245, 27, 546, 215, -1234]

In [4]:
l

[23245, 27, 546, 215, -1234]

In [5]:
print(l)

[23245, 27, 546, 215, -1234]


In [6]:
l[0]

23245

In [7]:
l[1:]

[27, 546, 215, -1234]

In [8]:
l[0:2]

[23245, 27]

In [9]:
l[::2]

[23245, 546, -1234]

In [10]:
l

[23245, 27, 546, 215, -1234]

In [11]:
#-------

In [16]:
l

[23245, 27, 546, 215, -1234]

In [17]:
import numpy as np

In [18]:
a = np.array(l)

In [19]:
a

array([23245,    27,   546,   215, -1234])

In [20]:
print(a)

[23245    27   546   215 -1234]


In [21]:
a[2:]

array([  546,   215, -1234])

In [22]:
a[2:4]

array([546, 215])

In [23]:
print(a)

[23245    27   546   215 -1234]


In [24]:
a[2:5]

array([  546,   215, -1234])

In [25]:
a[2:6]

array([  546,   215, -1234])

In [27]:
b = a[2:4]

In [28]:
b

array([546, 215])

In [29]:
b[0]

546

In [30]:
b[1]

215

In [32]:
b[:]

array([546, 215])

In [33]:
b[:] = 111

In [34]:
b

array([111, 111])

In [35]:
a

array([23245,    27,   111,   111, -1234])

In [36]:
c = a.copy()

In [37]:
c

array([23245,    27,   111,   111, -1234])

In [38]:
print(c)

[23245    27   111   111 -1234]


In [39]:
c[0] = 0

In [40]:
c

array([    0,    27,   111,   111, -1234])

In [41]:
a

array([23245,    27,   111,   111, -1234])